#------------------------------------------------------------------------------
# Dockerized Redcap for deploying in a variety of environments
#------------------------------------------------------------------------------

#The Containers in the System:
# 1) [base: tutum/apache-php] <-- Redcap
# 2) [base: /mysql] 


#------------------------------------------------------------------------------
# Database Container: MySQL
#------------------------------------------------------------------------------

FROM tutum/mysql

MAINTAINER Amos Folarin <amosfolarin@gmail.com>





